version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data 

  discountdb:
    container_name: discountdb
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Dip.BS@123
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  orderdb:
    container_name: orderdb
    environment:
      MSSQL_SA_PASSWORD: "Dip.BS@123"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"
    

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=dipesh@bigscal.com
      - PGADMIN_DEFAULT_PASSWORD=Dip.BS@123
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin 

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    ports:
      - "8000:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
      - "RabbitMq:HostUrl=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8001:80"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=Dip.BS@123;"
    ports:
      - "8002:80"

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=Dip.BS@123;"
    ports:
      - "8003:80"

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=orderdb;Database=Orderdb;User Id=sa;Password=Dip.BS@123;MultipleActiveResultSets=True;TrustServerCertificate=True"
      - "RabbitMq:HostUrl=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8004:80"

  ocelotapigateway:
    container_name: ocelotapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8010:80"

  shopping.aggregator:
    container_name: shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "AppSettings:CatalogUrl=http://catalog.api/api/"
      - "AppSettings:BasketUrl=http://basket.api/api/"
      - "AppSettings:OrderingUrl=http://ordering.api/api/"
    ports:
      - "8005:80"